input_select:
  chromecast_radio:
    name: "Select Speakers:"
    options:
      - Stofa
      - Græjur
      - Svefnherbergi
      - Bað
      - Eldhús
      - Allstaðar
    initial: Bað
    icon: mdi:speaker-wireless

  radio_station:
    name: "Select Radio Station:"
    options:
      - Rás 1
      - Rás 2
      - X-ið
      - Bylgjan
      - FM 957
    initial: Rás 2
    
input_number: 
  volume_radio:
    name: Volume
    icon: mdi:volume-high
    min: 0
    max: 1
    step: 0.05 
    
script:
  radio538:
    alias: Play Radio on Chromecast Audio
    sequence:
      - service: media_player.play_media
        data_template:
          entity_id: >
            {% if is_state("input_select.chromecast_radio", "Stofa") %} media_player.living_room_speaker
            {% elif is_state("input_select.chromecast_radio", "Græjur") %} media_player.stereo
            {% elif is_state("input_select.chromecast_radio", "Svefnherbergi") %} media_player.bedroom_speaker
            {% elif is_state("input_select.chromecast_radio", "Bað") %} media_player.bathroom_speaker
            {% elif is_state("input_select.chromecast_radio", "Eldhús") %} media_player.kitchen_speaker
            {% elif is_state("input_select.chromecast_radio", "Allstaðar") %} media_player.home_group
            {% endif %}
          media_content_id: >
            {% if is_state("input_select.radio_station", "Rás 1") %} http://netradio.ruv.is/ras1.mp3
            {% elif is_state("input_select.radio_station", "Rás 2") %} http://netradio.ruv.is/ras2.mp3
            {% elif is_state("input_select.radio_station", "X-ið") %} http://icecast.visir.is:8000/orbbylgjan.aac
            {% elif is_state("input_select.radio_station", "Bylgjan") %} http://icecast.visir.is:8000/orbXid.aac
            {% elif is_state("input_select.radio_station", "FM 957") %} http://icecast.visir.is:8000/orbFm957.aac
            {% endif %}
          media_content_type: "audio/mp4"
          
  stop_radio:
    alias: Stop radio
    sequence:
      service: media_player.media_stop
      data_template:
        entity_id: >
            {% if is_state("input_select.chromecast_radio", "Stofa") %} media_player.living_room_speaker
            {% elif is_state("input_select.chromecast_radio", "Græjur") %} media_player.stereo
            {% elif is_state("input_select.chromecast_radio", "Svefnherbergi") %} media_player.bedroom_speaker
            {% elif is_state("input_select.chromecast_radio", "Bað") %} media_player.bathroom_speaker
            {% elif is_state("input_select.chromecast_radio", "Eldhús") %} media_player.kitchen_speaker
            {% elif is_state("input_select.chromecast_radio", "Allstaðar") %} media_player.home_group
            {% endif %}
          
automation:
  - alias: 'Set Radio Volume'
    trigger:
      platform: state
      entity_id: input_number.volume_radio
    action:
      service: media_player.volume_set
      data_template:
        entity_id: >
          {% if is_state("input_select.chromecast_radio", "Stofa") %} media_player.living_room_speaker
          {% elif is_state("input_select.chromecast_radio", "Græjur") %} media_player.stereo
          {% elif is_state("input_select.chromecast_radio", "Svefnherbergi") %} media_player.bedroom_speaker
          {% elif is_state("input_select.chromecast_radio", "Bað") %} media_player.bathroom_speaker
          {% elif is_state("input_select.chromecast_radio", "Eldhús") %} media_player.kitchen_speaker
          {% elif is_state("input_select.chromecast_radio", "Allstaðar") %} media_player.home_group
          {% endif %}
        volume_level: '{{  states.input_number.volume_radio.state  }}' 
